spring:
  profiles:
    active: dev
  servlet:
    multipart:
      # ????????
      max-file-size: 5000MB
      # ????????
      max-request-size: 1000MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    #?????
    database: 0
    jedis:
      pool:
        #?????
        max-active: 15
        #????????(???????)
        max-wait: -1
        #????
        max-idle: 15
        #????
        min-idle: 0
mybatis:
  type-aliases-package: src.main.java.com.bili.entity
  # XML??
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????
    map-underscore-to-camel-case: true